import type { ZielGraphDaten } from '../types'

// Feste Beispieldaten: ein erfundenes Projekt (ein Web-Shop). Sie zeigen jede
// Art von Zeile einmal: erledigt, läuft, bereit, teilweise blockiert, blockiert,
// aufklappbares Bündel, Chat-Marke, „wartet auf“-Linie, zwei Dauerläufer und die
// Bahnen einer zweiten Person. Ein späterer Schritt ersetzt dieses Objekt durch
// abgeleitete Daten derselben Form.

export const STAMM = 'stamm'

export const BEISPIEL: ZielGraphDaten = {
  endziel: 'Endziel: der Shop im Betrieb',

  personen: [
    { id: 'ich', name: 'Ich' },
    { id: 'person-2', name: 'Person 2' },
  ],

  bahnen: [
    {
      id: 'kat',
      name: 'Katalog',
      person: 'ich',
      art: 'ziel',
      begonnen: true,
      farbe: { hell: '#0b7285', dunkel: '#5cc4d6' },
    },
    {
      id: 'kas',
      name: 'Kasse',
      person: 'ich',
      art: 'ziel',
      begonnen: true,
      farbe: { hell: '#2f9e44', dunkel: '#7fd992' },
    },
    {
      id: 'suc',
      name: 'Suche',
      person: 'ich',
      art: 'ziel',
      begonnen: false,
      farbe: { hell: '#1c7ed6', dunkel: '#7fb8f5' },
    },
    {
      id: 'btr',
      name: 'Betrieb',
      person: 'ich',
      art: 'dauer',
      begonnen: true,
      farbe: { hell: '#a3336b', dunkel: '#ee8fbd' },
    },
    {
      id: 'wkz',
      name: 'Werkzeug',
      person: 'ich',
      art: 'dauer',
      begonnen: true,
      farbe: { hell: '#6b4fa0', dunkel: '#b9a3e6' },
    },
    {
      id: 'imp',
      name: 'Import',
      person: 'person-2',
      art: 'dauer',
      begonnen: true,
      farbe: { hell: '#b3541e', dunkel: '#f0a070' },
    },
    {
      id: 'tst',
      name: 'Tests',
      person: 'person-2',
      art: 'dauer',
      begonnen: true,
      farbe: { hell: '#7a6a1f', dunkel: '#d6c66a' },
    },
  ],

  schritte: [
    // Hinter uns
    {
      id: 'grundstock',
      art: 'erledigt',
      bahn: 'kat',
      zone: 'hinter',
      titel: 'Grundstock: 13 Produktseiten fertig',
      meta: '',
    },
    {
      id: 'zahlarten',
      art: 'erledigt',
      bahn: 'kas',
      zone: 'hinter',
      titel: 'Zahlarten geklärt und 5 Entwürfe',
      meta: '',
    },
    {
      id: 'tests-ci',
      art: 'erledigt',
      bahn: 'tst',
      zone: 'hinter',
      titel: 'Testlauf in der CI eingerichtet',
      meta: 'Beispielzeile · Person 2',
    },

    // Jetzt möglich
    {
      id: 'katalog-texte',
      art: 'laeuft',
      bahn: 'kat',
      zone: 'jetzt',
      titel: 'Katalog-Texte abnehmen',
      meta: '#5 · wartet auf dich',
      chat: 'wartet',
    },
    {
      id: 'recherchen',
      art: 'bereit',
      bahn: 'kat',
      zone: 'jetzt',
      titel: '8 Recherchen zu den Kategorien',
      meta: '#8 bis #19 · 8 von 8 bereit',
      tickets: [
        '#8 · Schuhe: Größen als Variante oder Filter',
        '#9 · Jacken: Farbgruppen',
        '#11 · Taschen: Leder oder Stoff',
        '#13 · Taschen: Griff einzeln, im Set oder beides',
        '#14 · Taschen: Maße in cm gegen Zoll',
        '#15 · Schuhe: Pflegehinweis am Produkt oder im Text',
        '#18 · Schuhe: Sondergrößen',
        '#19 · Hosen: Längen zu Bundweite 3',
      ],
    },
    {
      id: 'warenkorb',
      art: 'laeuft',
      bahn: 'kas',
      zone: 'jetzt',
      titel: 'Entwurf Warenkorb-Regeln',
      meta: '#21 · läuft',
      chat: 'laeuft',
    },
    {
      id: 'gutscheine',
      art: 'bereit',
      bahn: 'kas',
      zone: 'jetzt',
      titel: 'Entwurf Gutschein-Einlösung',
      meta: '#22 · bereit',
    },
    {
      id: 'suchfelder',
      art: 'bereit',
      bahn: 'suc',
      zone: 'jetzt',
      titel: 'Suchfelder und Sortierung',
      meta: '#25, #26 · 2 von 2 bereit',
      tickets: [
        '#25 · Suche: Preis als eigenes Feld',
        '#26 · Suche: Sortierung nach Beliebtheit',
      ],
    },
    {
      id: 'ladezeit',
      art: 'bereit',
      bahn: 'btr',
      zone: 'jetzt',
      titel: 'Ladezeit der Startseite senken',
      meta: '#27 · bereit',
    },
    {
      id: 'build-skripte',
      art: 'teilweise',
      bahn: 'wkz',
      zone: 'jetzt',
      titel: 'Umbau der Build-Skripte',
      meta: '1 von 3 erledigt · Rest wartet auf Probelauf #30',
      chat: 'wartet',
      wartetAuf: 'lasttest',
    },
    {
      id: 'import-umzug',
      art: 'laeuft',
      bahn: 'imp',
      zone: 'jetzt',
      titel: 'Import: Umzug in Etappen',
      meta: 'Beispielzeile · Person 2',
    },
    {
      id: 'tests-daten',
      art: 'bereit',
      bahn: 'tst',
      zone: 'jetzt',
      titel: 'Tests: Testdaten bremsen den Lauf',
      meta: 'Beispielzeile · Person 2',
    },

    // Später
    {
      id: 'rueckfragen',
      art: 'blockiert',
      bahn: 'kat',
      zone: 'spaeter',
      titel: '10 Rückfragen an den Einkauf',
      meta: '#1, #32 bis #40 · wartet auf Auskunft',
    },
    {
      id: 'katalog-bilder',
      art: 'blockiert',
      bahn: 'kat',
      zone: 'spaeter',
      titel: 'Katalog: Bilder für alle Kategorien',
      meta: '#6 · blockiert',
    },
    {
      id: 'kasse-rechnungen',
      art: 'blockiert',
      bahn: 'kas',
      zone: 'spaeter',
      titel: 'Kasse: Block Rechnungen',
      meta: '#23 · vermutet: wartet auf die Entwürfe',
    },

    // Gemeinsame Bahn ab dem Treffpunkt
    {
      id: 'treffpunkt',
      art: 'treffpunkt',
      bahn: STAMM,
      titel: 'Treffpunkt: Großer Umbau',
      meta: 'sobald Katalog, Kasse und Suche fertig sind',
    },
    {
      id: 'lasttest',
      art: 'stamm',
      bahn: STAMM,
      titel: 'Lasttest',
      meta: 'Lasttest 2 · #31',
    },
    {
      id: 'lager',
      art: 'stamm',
      bahn: STAMM,
      titel: 'Lageranbindung',
      meta: 'noch nicht ausgearbeitet',
    },
    {
      id: 'versand',
      art: 'stamm',
      bahn: STAMM,
      titel: 'Versandabgleich',
      meta: 'noch nicht ausgearbeitet',
    },
    {
      id: 'endziel',
      art: 'endziel',
      bahn: STAMM,
      titel: 'Endziel: der Shop im Betrieb',
      meta: '',
    },
  ],

  uebersicht: [
    {
      id: 'ziel-kat',
      art: 'laeuft',
      bahn: 'kat',
      titel: 'Katalog füllen',
      meta: '12 offen · 5 bereit · 1 Chat',
    },
    {
      id: 'ziel-kas',
      art: 'laeuft',
      bahn: 'kas',
      titel: 'Kasse bauen',
      meta: '6 offen · 3 bereit · 1 Chat',
    },
    {
      id: 'ziel-suc',
      art: 'bereit',
      bahn: 'suc',
      titel: 'Suche einrichten',
      meta: '4 offen · 2 bereit',
    },
    {
      id: 'ziel-btr',
      art: 'bereit',
      bahn: 'btr',
      titel: 'Betrieb · Dauerläufer',
      meta: '9 offen · 4 bereit',
    },
    {
      id: 'ziel-wkz',
      art: 'teilweise',
      bahn: 'wkz',
      titel: 'Werkzeug · Dauerläufer',
      meta: '3 offen · 1 Chat',
    },
    {
      id: 'ziel-imp',
      art: 'laeuft',
      bahn: 'imp',
      titel: 'Import umziehen',
      meta: 'Beispielzeile · Person 2',
    },
    {
      id: 'ziel-tst',
      art: 'bereit',
      bahn: 'tst',
      titel: 'Tests · Dauerläufer',
      meta: 'Beispielzeile · Person 2',
    },
    {
      id: 'treffpunkt',
      art: 'treffpunkt',
      bahn: STAMM,
      titel: 'Treffpunkt: Großer Umbau',
      meta: '',
    },
    {
      id: 'lasttest',
      art: 'stamm',
      bahn: STAMM,
      titel: 'Lasttest',
      meta: '5 offen · 3 blockiert',
    },
    {
      id: 'lager',
      art: 'stamm',
      bahn: STAMM,
      titel: 'Lageranbindung',
      meta: '2 offen',
    },
    {
      id: 'versand',
      art: 'stamm',
      bahn: STAMM,
      titel: 'Versandabgleich',
      meta: '1 offen',
    },
    {
      id: 'endziel',
      art: 'endziel',
      bahn: STAMM,
      titel: 'Endziel: der Shop im Betrieb',
      meta: '',
    },
  ],
}
